# Generated by Django 5.0.1 on 2024-01-24 16:04

import datetime
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='номер телефона')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user_pictures/', verbose_name='аватарка')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('address', models.TextField(verbose_name='адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='номер телефона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'салон',
                'verbose_name_plural': 'салоны',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('service_type', models.CharField(choices=[('HS', 'Парикмахерские услуги'), ('MU', 'Макияж'), ('NS', 'Ногтевой сервис')], db_index=True, max_length=2, verbose_name='тип услуги')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
                ('is_archived', models.BooleanField()),
                ('shop', models.ManyToManyField(related_name='services', to='beauty_city_app.shop', verbose_name='салоны')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('profile_picture', models.ImageField(upload_to='', verbose_name='аватарка')),
                ('services', models.ManyToManyField(related_name='services', to='beauty_city_app.service', verbose_name='услуги')),
            ],
            options={
                'verbose_name': 'специалист',
                'verbose_name_plural': 'специалисты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата посещения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beauty_city_app.client', verbose_name='клиент')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beauty_city_app.specialist', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.TimeField(choices=[(datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00')], verbose_name='время')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='beauty_city_app.shop', verbose_name='салон')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='beauty_city_app.specialist', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'временной слот',
                'verbose_name_plural': 'временные слоты',
                'unique_together': {('date', 'time', 'specialist')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
                ('is_paid', models.BooleanField(default=False, verbose_name='запись оплачена')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty_city_app.client', verbose_name='клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beauty_city_app.service', verbose_name='услуга')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='beauty_city_app.timeslot', verbose_name='временной слот')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
