# Generated by Django 5.0.1 on 2024-01-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, verbose_name='отзыв'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='аватарка'),
        ),
    ]
